import {
  sign as cryptoSign,
  createPrivateKey,
  createHash,
  randomBytes,
  randomUUID,
} from 'node:crypto';
import { deriveKeyId } from '../crypto/svid.js';
import { validateSpiffeId, TRUST_DOMAIN } from '../crypto/spiffe.js';
import type { VanePassportClaims } from './types.js';

export const PASSPORT_AUDIENCE = 'vane:passport:v1';
export const PASSPORT_TTL_DEFAULT = 3600; // 1 hour
// Hard bounds enforced at issuance. Short TTLs are the primary revocation
// defense — an expired passport is always rejected regardless of revocation
// list availability, so keeping the cap low limits blast radius.
export const PASSPORT_TTL_MIN = 300;      // 5 minutes
export const PASSPORT_TTL_MAX = 3600;     // 1 hour

// 128-bit value rendered as 32 hex chars. Used to validate caller-supplied nonces.
const NONCE_RE = /^[0-9a-f]{32}$/i;
// SHA-256 digest rendered as 64 hex chars.
const REQUEST_HASH_RE = /^[0-9a-f]{64}$/i;

function b64url(s: string): string {
  return Buffer.from(s, 'utf8').toString('base64url');
}

/**
 * Client-side helper that mints a fresh 128-bit nonce (hex-encoded).
 *
 * The nonce is meant to be generated by the *caller* at issuance time and
 * passed into {@link issuePassport}. Vane never fabricates a nonce on the
 * caller's behalf — sender-constraint requires the requesting party to bind
 * the value it will later present as `expectedNonce`.
 */
export function generateNonce(): string {
  return randomBytes(16).toString('hex'); // 16 bytes = 128 bits
}

export interface CanonicalRequest {
  method: string;            // HTTP method (case-insensitive; canonicalized to upper)
  url: string;               // full request URL the passport is bound to
  body?: string | Buffer;    // raw request body, if any
}

/**
 * Computes the canonical request hash used for request binding:
 *
 *   SHA-256( METHOD + "|" + url + "|" + SHA-256(body) )
 *
 * Both the issuer (to populate `vane.requestHash`) and the verifier (to derive
 * `expectedRequestHash` from the live request) call this so the two values are
 * byte-identical for the same logical request.
 */
export function computeRequestHash(req: CanonicalRequest): string {
  const bodyHash = createHash('sha256').update(req.body ?? '').digest('hex');
  const canonical = `${req.method.toUpperCase()}|${req.url}|${bodyHash}`;
  return createHash('sha256').update(canonical).digest('hex');
}

export interface IssuePassportOptions {
  agentId: string;
  agentSpiffeId: string;
  org: string;
  orgSpiffeId: string;
  scopes: string[];
  delegationChain: string[];
  delegationId?: string;
  ttl?: number;          // seconds, defaults to PASSPORT_TTL_DEFAULT

  // ── Sender-constraint inputs (all optional) ──────────────────────────────────
  // Supplying any of these turns the resulting bearer token into a
  // sender-constrained credential. Omitting them preserves the legacy
  // plain-bearer behavior.
  nonce?: string;        // caller-supplied 128-bit hex value; NOT generated by Vane
  audience?: string;     // intended recipient server, e.g. "https://api.example.com"
  requestHash?: string;  // SHA-256 hex of the canonical request (see computeRequestHash)

  privateKeyPem: string;
  publicKeyPem: string;
}

/**
 * Issues a Vane Agent Passport (CAP+JWT).
 *
 * The resulting token is a standard EdDSA JWT verifiable by any party that
 * holds the CA public key — no network call to Vane is required.
 *
 * Security invariants:
 *   - alg is hard-coded to EdDSA; no algorithm confusion is possible
 *   - typ is "CAP+JWT" — distinct from SVID tokens (typ "JWT")
 *   - aud is "vane:passport:v1" — prevents replay across token types
 *   - nbf equals iat — no pre-dating
 *   - delegationChain tail MUST equal agentSpiffeId before signing
 *   - sender-constraint claims (nonce / audience / requestHash) are validated
 *     for shape here and bound into the signed payload when supplied
 */
export function issuePassport(opts: IssuePassportOptions): string {
  if (!validateSpiffeId(opts.agentSpiffeId)) {
    throw new Error(`Invalid agent SPIFFE ID: ${opts.agentSpiffeId}`);
  }
  if (!validateSpiffeId(opts.orgSpiffeId)) {
    throw new Error(`Invalid org SPIFFE ID: ${opts.orgSpiffeId}`);
  }
  if (opts.scopes.length === 0) {
    throw new Error('Passport must include at least one scope');
  }
  if (opts.delegationChain.length === 0) {
    throw new Error('Passport must include a delegation chain');
  }
  const chainTail = opts.delegationChain[opts.delegationChain.length - 1];
  if (chainTail !== opts.agentSpiffeId) {
    throw new Error(
      `delegationChain tail (${chainTail}) must equal agentSpiffeId (${opts.agentSpiffeId})`,
    );
  }

  // Sender-constraint shape validation. A malformed constraint is rejected at
  // issuance so a passport can never carry a value the verifier cannot match.
  if (opts.nonce !== undefined && !NONCE_RE.test(opts.nonce)) {
    throw new Error('Passport nonce must be a 128-bit hex string (32 hex chars)');
  }
  if (opts.audience !== undefined && (typeof opts.audience !== 'string' || opts.audience.length === 0)) {
    throw new Error('Passport audience must be a non-empty string');
  }
  if (opts.requestHash !== undefined && !REQUEST_HASH_RE.test(opts.requestHash)) {
    throw new Error('Passport requestHash must be a SHA-256 hex string (64 hex chars)');
  }

  const requestedTtl = opts.ttl ?? PASSPORT_TTL_DEFAULT;
  if (requestedTtl < PASSPORT_TTL_MIN || requestedTtl > PASSPORT_TTL_MAX) {
    throw new Error(
      `Passport TTL ${requestedTtl}s is out of bounds [${PASSPORT_TTL_MIN}, ${PASSPORT_TTL_MAX}]`,
    );
  }
  const ttl = requestedTtl;
  const now = Math.floor(Date.now() / 1000);
  const kid = deriveKeyId(opts.publicKeyPem);

  const header = b64url(JSON.stringify({ alg: 'EdDSA', typ: 'CAP+JWT', kid }));

  const claims: VanePassportClaims = {
    iss: `spiffe://${TRUST_DOMAIN}/ca`,
    sub: opts.agentSpiffeId,
    aud: [PASSPORT_AUDIENCE],
    jti: randomUUID(),
    iat: now,
    exp: now + ttl,
    nbf: now,
    vane: {
      v: 1,
      agentId: opts.agentId,
      org: opts.org,
      orgSpiffeId: opts.orgSpiffeId,
      scopes: opts.scopes,
      delegationChain: opts.delegationChain,
      ...(opts.delegationId !== undefined && { delegationId: opts.delegationId }),
      ...(opts.nonce !== undefined && { nonce: opts.nonce }),
      ...(opts.audience !== undefined && { aud: opts.audience }),
      ...(opts.requestHash !== undefined && { requestHash: opts.requestHash }),
    },
  };

  const payload = b64url(JSON.stringify(claims));
  const signingInput = `${header}.${payload}`;
  const sig = cryptoSign(null, Buffer.from(signingInput), createPrivateKey(opts.privateKeyPem))
    .toString('base64url');

  return `${signingInput}.${sig}`;
}
